### ISSUE TITLE
Write Rebecca Dialog w/ Austin 

### ISSUE THREAD

**Issue by Anesti-Zoi** [Anesti-Zoi/SSVC#7]
Weight: 3

- [x] Create dialog w/ Austin and Rebecca for CH2 
- [x] Reference: https://drive.google.com/drive/folders/1-lE3cgD0ZjEzo8Xm7cIJvP1bXIJWwebj
- [x] Link file w/ G-Drive

Reviewer: 
@Dureidureii

**Comment by Anesti-Zoi** [comment]
https://docs.google.com/document/d/1G9VfT9J_G3iGtSTas1k9Cxv-Kll9xblk2rs8fmJn41c/edit

{

“Oh, you’re back.”

“Another elk?”

‘Austin nods’

“Quite the huntsman aren’t you?” - Austin places the food away for her 

“Thank you again.” - “It’s nothing.”

“It’s something to me, my children are healthy and fed.”

“Sorry, I didn’t mean that. It’s second nature to me.”

- Austin waves at the child, he moves to leave

“If you make any bread, I’ll trade for it. Be safe.”

“I’ll let you know first, blessings upon you.”

}

**Comment by Dureidureii** [comment]
Here’s a check for the dialogue. I tweaked some of them but if these don’t look okay I’ll switch it to the original script: https://drive.google.com/file/d/1hfu2CkE2lb2l8HNpYAN7IXbfDlOIysV-/view?usp=drivesdk

**Comment by Anesti-Zoi** [comment]
![CH_02_Output_004](https://user-images.githubusercontent.com/87678816/127939054-7883bffb-cf22-4013-a9c4-3bfb41448005.png) 

I think changing the dialog here from "Did you get us another elk?" to "Another elk? That's three this week."
